// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package repository

import (
	"database/sql"

	"github.com/google/uuid"
)

type Cart struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type CartItem struct {
	ID        uuid.UUID     `json:"id"`
	CartID    uuid.NullUUID `json:"cart_id"`
	ProductID uuid.NullUUID `json:"product_id"`
	Quantity  int32         `json:"quantity"`
}

type Product struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	Category    string         `json:"category"`
	Description sql.NullString `json:"description"`
}

type User struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
}
