// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package repository

import (
	"context"
)

type Querier interface {
	GetProducts(ctx context.Context) ([]Product, error)
	Login(ctx context.Context, email string) (LoginRow, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) error
}

var _ Querier = (*Queries)(nil)
