// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const login = `-- name: Login :one
SELECT id, password FROM users WHERE email = $1
`

type LoginRow struct {
	ID       uuid.UUID `json:"id"`
	Password string    `json:"password"`
}

func (q *Queries) Login(ctx context.Context, email string) (LoginRow, error) {
	row := q.db.QueryRowContext(ctx, login, email)
	var i LoginRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const registerUser = `-- name: RegisterUser :exec
INSERT INTO users (name, email, password) 
VALUES ($1, $2, $3)
`

type RegisterUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) error {
	_, err := q.db.ExecContext(ctx, registerUser, arg.Name, arg.Email, arg.Password)
	return err
}
