// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Cart struct {
	ID        int32
	UserID    sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type CartItem struct {
	ID        int32
	CartID    sql.NullInt32
	ProductID sql.NullInt32
	Quantity  int32
}

type Product struct {
	ID          int32
	Name        string
	Price       string
	Stock       int32
	Description sql.NullString
}

type User struct {
	ID       int32
	Name     string
	Email    string
	Password string
}
